server:
  port: 1234

spring:
  application:
    name: EventManager-api
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: never
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        default_schema: ${DB_SCHEMA}
    show-sql: false